name: CI Workflow
# mainブランチに変更がプッシュされたときにワークフローをトリガー
on:
  push:
    branches:
     - main
     
jobs:
  build:
    runs-on: self-hosted  # セルフホステッドランナーを使用
    steps:
     - name: Checkout code
       uses: actions/checkout@v2  # リポジトリのコードをチェックアウト

     - name: Run build script
       run: |
         echo "Running build on self-hosted runner"
         ./build.sh
